name: Post merge

on:
  push:
    branches: [ master ]

jobs:
  allChecks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run all checks
      run: ./gradlew check --stacktrace

    - uses: actions/upload-artifact@v2
      with:
        name: lint-report.html
        path: app/build/reports/lint-results.html
      
    - name: Upload Test results
      uses: actions/upload-artifact@v1
      with:
        name: test-report.html
        path: app/build/reports/tests/testDebugUnitTest/index.html
    
  instrumentationTests:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Run Instrumentation tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew connectedCheck --stacktrace
        
        
  deploy:
    runs-on: ubuntu-latest
    needs: [allChecks, instrumentationTests]

    steps:
    - uses: actions/checkout@v2

    - name: Build Snapshot
      run: ./gradlew assemble --stacktrace
    
    - uses: actions/upload-artifact@v2
      with:
        name: app-release-SNAPSHOT.apk
        path: app/build/outputs/apk/release/app-release-unsigned.apk
